### ISSUE TITLE
Sản phẩm gift trên slide lưu các thông tin chưa được xử lý khi add to cart

### ISSUE THREAD

**Issue by htmyheart** [htmyheart/magento-development#14]
Trong html của sản phẩm gift có giá trị qty, giá trị này có thể bị lợi dụng để set bằng tay dưới client để set qty cho item add to cart.

Phải xử lý dữ liệu lại phía server cho đúng. Các bước xử lý:
* phía frontend bỏ rule_id, rule_name ra khỏi html
* phía server cắt chuỗi freegift_parent_key để lấy lại thông tin rule
* xử lý qty cho phù hợp với thông tin rule (chú ý phần buy_x get_y)

![image.png](https://images.zenhubusercontent.com/5af3be284b5806bc2bd29298/071d1c4b-f373-4e0b-80a4-a35eb1942a3e)

**Comment by tudn9x** [comment]
Hướng dẫn:
- Sử dụng event before add to cart để add thêm thông tin cho gift (infoBuyRequest)
- Tìm xem sản phẩm gift này là của sản phẩm thường nào bằng cách so sánh tham số truyền lên (freegift_parent_key) với thông tin freegift_keys của sản phẩm thường.
- Sau khi đã xác định được item của sản phẩm thường trong cart, trích thông tin freegift_rule_data trong infoBuyRequest ra.
- Từ thông tin freegift_rule_data truyền qua helper để lấy thông tin gift data.
- Sau khi có được thông tin gift data, sử dụng id của sản phẩm đang add to cart xác định là gift data nào.
- Tiếp tục sử dụng gift data đó để thêm, sửa thông tin params cho đúng sau đó để tự động cho magento add to cart.
![image](https://user-images.githubusercontent.com/4941829/41028616-05377d26-69a4-11e8-9282-6a7fb8ed656b.png)
