### ISSUE TITLE
Tại mini cart, update số lượng của sản phẩm thường nhưng sản phẩm gift không được update theo

### ISSUE THREAD

**Issue by htmyheart** [htmyheart/magento-development#16]
Tại mini cart. Phần update sản phẩm gift đã chạy đúng với số lượng quy định. Nhưng khi update số lượng của sản phẩm thường, sản phẩm gift đang không được update theo.  (code bị thiếu cho trường hợp này).

![image.png](https://images.zenhubusercontent.com/5af3be284b5806bc2bd29298/263b501e-8fa2-40fb-ae10-fa7c61cea953)

**Comment by syluu** [comment]
Đã fix.
Solution: bắt event controller update minicart, dẫn tới 1 action và thêm action đó vào etc/frontend/sections.xml
